name: Management workflows of this project

on:
  push:
    branch: [master]

permissions:
  contents: read
  packages: write
  statuses: write

jobs:
  release-project:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.1
      - run: flutter --version

      - name: Build the APK
        run: |
          git config --global url."https://${{ secrets.GH_PAT_UNISTREAM_FLUTTER }}@github.com/".insteadOf "https://github.com/"
          flutter pub get
          flutter build apk --release
          zip --junk-paths app-release build/app/outputs/flutter-apk/app-release.apk

      - name: Create Github release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body:
            Change in this Release
              - First Change
              - Second Change
          draft: false
          prerelease: false

      - name: Upload release APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./app-release.zip
          asset_name: app-release-${{ github.run_number }}.zip
          asset_content_type: application/zip
      